# Generated by Django 4.2.14 on 2024-08-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("gender", models.CharField(default="", max_length=50)),
                ("dob", models.DateField(default="")),
                ("school", models.CharField(default="", max_length=200)),
                ("college", models.CharField(default="", max_length=200)),
                ("company", models.CharField(default="", max_length=200)),
            ],
        ),
    ]
