# Generated by Django 4.2.14 on 2024-08-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_loginto_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=100)),
                ("suggestion", models.TextField()),
            ],
        ),
    ]
