# Generated by Django 4.2.14 on 2024-08-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_suggestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("to", models.CharField(max_length=100)),
                ("state", models.BooleanField(default=False)),
                ("frm", models.CharField(max_length=100)),
            ],
        ),
    ]
