# Generated by Django 4.2.14 on 2024-08-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="friends",
            name="of",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="friends",
            name="friend",
            field=models.CharField(default="", max_length=100),
        ),
    ]
