# Generated by Django 4.2.14 on 2024-08-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_friends_of_alter_friends_friend"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("phone", models.CharField(max_length=100)),
                ("textField", models.TextField(default="")),
                ("image", models.ImageField(default="", upload_to="images")),
            ],
        ),
    ]
