# Generated by Django 4.2.14 on 2024-08-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile", name="textField", field=models.TextField(),
        ),
    ]
