# Generated by Django 4.2.14 on 2024-08-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_profile_textfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="textField",
            field=models.TextField(blank=True, null=True),
        ),
    ]
